package com.example.ehcf.Appointments.Consulted.model

data class Consulted(
    val address: String?=null,
    val comments: String?=null,
    val created_at: String,
    val customer_comments:  String?=null,
    val customer_rating: String,
    val date:  String?=null,
    val description: String,
    val doctor_id: String,
    val doctor_name: String,
    val email: String,
    val hospital_logo: String?=null,
    val hospital_name:  String?=null,
    val id: String,
    val latitude: String?=null,
    val longitude:  String?=null,
    val patient_id: String,
    val payment_mode: String,
    val payment_name: String,
    val phone_number: String,
    val profile_image: String,
    val rating: String,
    val slug: String,
    val start_time: String,
    val status: String,
    val status_for_customer: String,
    val status_name: String,
    val time: String?=null,
    val title: String,
    val total_amount: String,
    val updated_at: String
)