package com.example.ehcf.Appointments.Cancelled.model

data class Cancelled(
    val address: Any,
    val comments: Any,
    val created_at: String,
    val customer_comments: Any,
    val customer_rating: String,
    val date: Any,
    val description: String,
    val doctor_id: String,
    val doctor_name: String,
    val email: String,
    val hospital_logo: Any,
    val hospital_name: Any,
    val id: String,
    val latitude: Any,
    val longitude: Any,
    val patient_id: String,
    val payment_mode: String,
    val payment_name: String,
    val phone_number: String,
    val profile_image: String,
    val rating: String,
    val slug: String,
    val start_time: String,
    val status: String,
    val status_for_customer: String,
    val status_name: String,
    val time: Any,
    val title: String,
    val total_amount: String,
    val updated_at: String
)