package com.example.ehcf.Appointments.UpComing.model

data class ResultHome(
    val btn_status: Int,
    val comments: Any,
    val consultation_type: String,
    val created_at: String,
    val customer_comments: Any,
    val customer_rating: String,
    val date: String,
    val doctor_id: String,
    val doctor_name: String?=null,
     val email: String,
    val member_name: String,
     val customer_name: String?=null,
    val id: String,
    val profile_picture: String,
    val prescriptionid: String,
    val member_id: String,
    val patient_id: String,
    val payment_mode: String,
    val payment_name: String,
    val phone_number: String,
    val profile_image: String,
    val rating: String,
    val slug: String,
    val status: String,
    val status_for_customer: String,
    val status_name: String,
    val time: String,
    val start_time: String,
    val end_time: String,
    val total: String,
    val updated_at: String
)